# Generated by Django 3.2 on 2023-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('execution_time', models.DateTimeField(auto_now_add=True, verbose_name='Срок выполнение')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
